#!/bin/sh

# Script to setup these dotfiles
# Then strap-after-setup is run
cd ~
echo "creating ~/bin for scripts"
mkdir -p ~/bin
echo "creating ~/Code for code"
mkdir -p ~/Code/go

echo "Link git config & git ignores"
ln -s ~/.dotfiles/.gitconfig ~/.gitconfig
ln -s ~/.dotfiles/.gitignore_global ~/.gitignore_global

echo "Link shell aliases and path"
ln -s ~/.dotfiles/.sh_aliases ~/.sh_aliases
ln -s ~/.dotfiles/.sh_path ~/.sh_path


echo "Source shell aliases and path"
echo "source ~/.sh_aliases" >> ~/.bashrc
echo "source ~/.sh_aliases" >> ~/.zshrc
echo "source ~/.sh_path" >> ~/.bashrc
echo "source ~/.sh_path" >> ~/.zshrc

echo "Setup z (jump around)"
mkdir -p ~/Code/github
cd ~/Code/
git clone https://github.com/rupa/z
cd
echo "source ~/Code/github/z/z.sh" >> ~/.bashrc
echo "source ~/Code/github/z/z.sh" >> ~/.zshrc


echo "Link vimrc"
ln -s ~/.dotfiles/.vimrc ~/.vimrc

echo "Install Vundle (vim plugin manager)"
mkdir -p ~/.vim/bundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

echo "Installing Vundle plugins"
vim +PluginInstall +qall

echo "Installing emacs"
brew tap d12frosted/emacs-plus
brew install emacs-plus
brew linkapps emacs-plus

echo "Install spacemacs (assumes emacs is installed)"
cd ~
mv .emacs.d .emacs.d.bak
mv .emacs .emacs.bak
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

echo "Link spacemacs config"
ln -s ~/.dotfiles/.spacemacs ~/.spacemacs

echo "script/setup DONE"
