#!/bin/sh

# Script to setup these dotfiles
# Run after the dotfiles are copied
# Then strap-after-setup is run

echo "Setting up shell aliases and path"
echo "source ~/.sh_aliases" >> ~/.bashrc
echo "source ~/.sh_aliases" >> ~/.zshrc
echo "source ~/.sh_path" >> ~/.bashrc
echo "source ~/.sh_path" >> ~/.zshrc

echo "Install Vundle (vim plugin manager)"
mkdir -p ~/.vim/bundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

echo "Installing Vundle plugins"
vim +PluginInstall +qall

echo "Installing emacs"
brew tap d12frosted/emacs-plus
brew install emacs-plus
brew linkapps emacs-plus

echo "Install spacemacs (assumes emacs is installed)"
cd ~
mv .emacs.d .emacs.d.bak
mv .emacs .emacs.bak
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

echo "Download, build, & install mosh (assumes build tools installed)"
curl https://mosh.org/mosh-1.3.2.tar.gz -o ~/mosh.tar.gz
tar -xzf ~/mosh.tar.gz
cd ~/mosh-1.3.2/
./configure
make
sudo make install

echo "Install nvm, node, & npm"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
nvm install node

echo "Install tldr"
npm install tldr

echo "DONE"
